# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

require "rake/testtask"
Rake::TestTask.new(:suture) do |t|
  t.libs << "lib"
  t.libs << "config"
  t.libs << "app"
  t.libs << "test"
  t.test_files = FileList["test/suture/**/*_test.rb"]
end
Rails.application.load_tasks
